AttendanceMS-Laravel/routes/web.php
<?php



use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FingerDevicesControlller;

Route::get('/', function () {
    return view('welcome');
})->name('welcome');
Route::get('attended/{user_id}', '\App\Http\Controllers\AttendanceController@attended' )->name('attended');
Route::get('attended-before/{user_id}', '\App\Http\Controllers\AttendanceController@attendedBefore' )->name('attendedBefore');
Auth::routes(['register' => false, 'reset' => false]);

Route::group(['middleware' => ['auth', 'Role'], 'roles' => ['admin']], function () {
    Route::resource('/employees', '\App\Http\Controllers\EmployeeController');
    Route::resource('/employees', '\App\Http\Controllers\EmployeeController');
    Route::get('/attendance', '\App\Http\Controllers\AttendanceController@index')->name('attendance');
  
    Route::get('/latetime', '\App\Http\Controllers\AttendanceController@indexLatetime')->name('indexLatetime');
    Route::get('/leave', '\App\Http\Controllers\LeaveController@index')->name('leave');
    Route::get('/overtime', '\App\Http\Controllers\LeaveController@indexOvertime')->name('indexOvertime');

    Route::get('/admin', '\App\Http\Controllers\AdminController@index')->name('admin');

    Route::resource('/schedule', '\App\Http\Controllers\ScheduleController');

    Route::get('/check', '\App\Http\Controllers\CheckController@index')->name('check');
    Route::get('/sheet-report', '\App\Http\Controllers\CheckController@sheetReport')->name('sheet-report');
    Route::post('check-store','\App\Http\Controllers\CheckController@CheckStore')->name('check_store');
    
    // Fingerprint Devices
    Route::resource('/finger_device', '\App\Http\Controllers\BiometricDeviceController');

    Route::delete('finger_device/destroy', '\App\Http\Controllers\BiometricDeviceController@massDestroy')->name('finger_device.massDestroy');
    Route::get('finger_device/{fingerDevice}/employees/add', '\App\Http\Controllers\BiometricDeviceController@addEmployee')->name('finger_device.add.employee');
    Route::get('finger_device/{fingerDevice}/get/attendance', '\App\Http\Controllers\BiometricDeviceController@getAttendance')->name('finger_device.get.attendance');
    // Temp Clear Attendance route
    Route::get('finger_device/clear/attendance', function () {
        $midnight = \Carbon\Carbon::createFromTime(23, 50, 00);
        $diff = now()->diffInMinutes($midnight);
        dispatch(new ClearAttendanceJob())->delay(now()->addMinutes($diff));
        toast("Attendance Clearance Queue will run in 11:50 P.M}!", "success");

        return back();
    })->name('finger_device.clear.attendance');
    

});

Route::group(['middleware' => ['auth']], function () {

    // Route::get('/home', 'HomeController@index')->name('home');



    

});

// Route::get('/attendance/assign', function () {
//     return view('attendance_leave_login');
// })->name('attendance.login');

// Route::post('/attendance/assign', '\App\Http\Controllers\AttendanceController@assign')->name('attendance.assign');


// Route::get('/leave/assign', function () {
//     return view('attendance_leave_login');
// })->name('leave.login');

// Route::post('/leave/assign', '\App\Http\Controllers\LeaveController@assign')->name('leave.assign');


// Route::get('{any}', 'App\http\controllers\VeltrixController@index');

AttendanceMS-Laravel/app/Models/FingerDevices.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FingerDevices extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        "name",
        "ip",
        "serialNumber",
    ];
}

AttendanceMS-Laravel/resources/views/admin/fingerDevices/create.blade.php
@extends('layouts.master')

@section('content')

    <div class="card">

        <div class="card-header">

            {{ trans('global.create') }} {{ trans('cruds.finger_device.title_singular') }}

        </div>

        <div class="card-body">

            <form method="POST" action="{{ route("finger_device.store") }}">

                @csrf

                <div class="form-group">

                    <label class="required" for="title">{{ trans('cruds.finger_device.fields.name') }}</label>

                    <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text"

                           name="name"

                           id="title" value="{{ old('name', '') }}" required>

                    @if($errors->has('name'))

                        <span class="text-danger">{{ $errors->first('name') }}</span>

                    @endif

                    <span class="help-block">{{ trans('cruds.finger_device.fields.name_helper') }}</span>

                </div>

                <div class="form-group">

                    <label class="required" for="ip">{{ trans('cruds.finger_device.fields.ip') }}</label>

                    <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text"

                           name="ip"

                           id="ip" value="{{ old('ip', '') }}" required>

                    @if($errors->has('ip'))

                        <span class="text-danger">{{ $errors->first('ip') }}</span>

                    @endif

                    <span class="help-block">{{ trans('cruds.finger_device.fields.ip_helper') }}</span>

                </div>

                <div class="form-group">

                    <button class="btn btn-danger" type="submit">

                        {{ trans('global.save') }}

                    </button>

                </div>

            </form>

        </div>

    </div>

@endsection

AttendanceMS-Laravel/resources/views/admin/fingerDevices/edit.blade.php
@extends('layouts.master')

@section('content')

    <div class="card">

        <div class="card-header">

            {{ trans('global.edit') }} {{ trans('cruds.finger_device.title_singular') }}

        </div>

        <div class="card-body">

            <form method="POST" action="{{ route("finger_device.update", $fingerDevice->id) }}">

                @csrf

                @method('PUT')

                <div class="form-group">

                    <label class="required" for="title">{{ trans('cruds.finger_device.fields.name') }}</label>

                    <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text"

                           name="name"

                           id="title" value="{{ old('name', $fingerDevice->name) }}" required>

                    @if($errors->has('name'))

                        <span class="text-danger">{{ $errors->first('name') }}</span>

                    @endif

                    <span class="help-block">{{ trans('cruds.finger_device.fields.name_helper') }}</span>

                </div>

                <div class="form-group">

                    <label class="required" for="ip">{{ trans('cruds.finger_device.fields.ip') }}</label>

                    <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text"

                           name="ip"

                           id="ip" value="{{ old('ip', $fingerDevice->ip) }}" required>

                    @if($errors->has('ip'))

                        <span class="text-danger">{{ $errors->first('ip') }}</span>

                    @endif

                    <span class="help-block">{{ trans('cruds.finger_device.fields.ip_helper') }}</span>

                </div>

                <div class="form-group">

                    <label class="required"

                           for="serialNumber">{{ trans('cruds.finger_device.fields.serialNumber') }}</label>

                    <input class="form-control {{ $errors->has('serialNumber') ? 'is-invalid' : '' }}" type="text"

                           name="serialNumber"

                           id="serialNumber" value="{{ old('serialNumber', $fingerDevice->serialNumber) }}" required>

                    @if($errors->has('serialNumber'))

                        <span class="text-danger">{{ $errors->first('serialNumber') }}</span>

                    @endif

                    <span class="help-block">{{ trans('cruds.finger_device.fields.serialNumber_helper') }}</span>

                </div>

                <div class="form-group">

                    <button class="btn btn-primary" type="submit">

                        {{ trans('global.update') }}

                    </button>

                </div>

            </form>

        </div>

    </div>

@endsection

AttendanceMS-Laravel/resources/views/admin/fingerDevices/index.blade.php
@extends('layouts.master')

@section('content')



        <div style="margin-bottom: 10px;" class="row">

            <div class="col-lg-12">

                <a class="btn btn-success" href="{{ route('finger_device.create') }}">

                    {{ trans('global.add') }} {{ trans('cruds.finger_device.title_singular') }}

                </a>

                {{-- <a class="btn btn-primary"

                   href="{{ route('finger_device.get.attendance') }}">

                    <i class="fas fa-cogs"></i>

                    Run Attendance Queue

                </a> --}}

                <a class="btn btn-primary"

                   href="{{ route('finger_device.clear.attendance') }}">

                    <i class="fas fa-cog"></i>

                    Clear device attendance

                </a>

            </div>

        </div>


    <div class="card">

        <div class="card-header">

            {{ trans('cruds.finger_device.title_singular') }} {{ trans('global.list') }}

        </div>



        <div class="card-body">

            <div class="table-rep-plugin">
                <div class="table-responsive mb-0" data-pattern="priority-columns">
                    <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                            
                    <thead class="thead-dark">

                    <tr>

                       

                        <th>

                            {{ trans('cruds.finger_device.fields.id') }}

                        </th>

                        <th>

                            {{ trans('cruds.finger_device.fields.name') }}

                        </th>

                        <th>

                            {{ trans('cruds.finger_device.fields.ip') }}

                        </th>

                        <th>

                            {{ trans('cruds.finger_device.fields.serialNumber') }}

                        </th>

                        <th>

                            Status

                        </th>

                        <th>
                            Actions

                        </th>

                    </tr>

                    </thead>

                    @php

                        $helper = new \App\Helpers\FingerHelper();

                    @endphp

                    <tbody>

                    @foreach($devices as $key => $finger_device)

                        <tr data-entry-id="{{ $finger_device->id }}">

                          

                            <td>

                                {{ $finger_device->id ?? '' }}

                            </td>

                            <td>

                                {{ $finger_device->name ?? '' }}

                            </td>

                            <td>

                                {{ $finger_device->ip ?? '' }}

                            </td>

                            <td>

                                {{ $finger_device->serialNumber ?? '' }}

                            </td>

                            <td>

                                @php

                                    $device = $helper->init($finger_device->ip);

                                @endphp

                                @if($helper->getStatus($device))

                                    <div class="badge badge-success">

                                        Active

                                    </div>

                                @else

                                    <div class="badge badge-danger">

                                        Deactivate

                                    </div>

                                @endif

                                

                                    <a class="btn btn-xs btn-outline-success"

                                       href="{{ route('finger_device.add.employee', $finger_device->id) }}">

                                        <i class="fas fa-plus"></i>

                                        Add Employee

                                    </a>
                                    
                                    <a class="btn btn-xs btn-outline-success"

                                       href="{{ route('finger_device.get.attendance', $finger_device->id) }}">

                                        <i class="fas fa-plus"></i>

                                        Get Attendance

                                    </a>

                                

                            </td>

                            <td>

                            
                                    <a class="btn btn-xs btn-primary"

                                       href="{{ route('finger_device.show', $finger_device->id) }}">

                                        {{ trans('global.view') }}

                                    </a>

                            



                              

                                    <a class="btn btn-xs btn-info"

                                       href="{{ route('finger_device.edit', $finger_device->id) }}">

                                        {{ trans('global.edit') }}

                                    </a>

                             



                              

                                    <form action="{{ route('finger_device.destroy', $finger_device->id) }}"

                                          method="POST"

                                          onsubmit="return confirm('{{ trans('global.areYouSure') }}');"

                                          style="display: inline-block;">

                                        <input type="hidden" name="_method" value="DELETE">

                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">

                                        <input type="submit" class="btn btn-xs btn-danger"

                                               value="{{ trans('global.delete') }}">

                                    </form>




                            </td>

                        </tr>

                    @endforeach

                    </tbody>

                </table>
                </div>
            </div>

        </div>

    </div>

@endsection

@section('scripts')

    @parent

    {{--    @livewireScripts--}}

    <script>

        // window.livewire.on('userStore', () => {

        //     $('#exampleModal').modal('hide');

        // });

        $(function () {

            let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)

            @can('finger_device_delete')

            let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'

            let deleteButton = {

                text: deleteButtonTrans,

                url: "{{ route('admin.finger_device.massDestroy') }}",

                className: 'btn-danger',

                action: function (e, dt, node, config) {

                    var ids = $.map(dt.rows({selected: true}).nodes(), function (entry) {

                        return $(entry).data('entry-id')

                    });



                    if (ids.length === 0) {

                        alert('{{ trans('global.datatables.zero_selected') }}')



                        return

                    }



                    if (confirm('{{ trans('global.areYouSure') }}')) {

                        $.ajax({

                            headers: {'x-csrf-token': _token},

                            method: 'POST',

                            url: config.url,

                            data: {ids: ids, _method: 'DELETE'}

                        })

                            .done(function () {

                                location.reload()

                            })

                    }

                }

            }

            dtButtons.push(deleteButton)

            @endcan



            $.extend(true, $.fn.dataTable.defaults, {

                orderCellsTop: true,

                order: [[1, 'desc']],

                pageLength: 100,

            });

            let table = $('.datatable-finger_device:not(.ajaxTable)').DataTable({buttons: dtButtons})

            $('a[data-toggle="tab"]').on('shown.bs.tab click', function (e) {

                $($.fn.dataTable.tables(true)).DataTable()

                    .columns.adjust();

            });



        })



    </script>

@endsection

AttendanceMS-Laravel/resources/views/admin/fingerDevices/show.blade.php
@extends('layouts.master')

@section('content')

    <div class="card">

        <div class="card-header">

            {{ trans('global.show') }} {{ trans('cruds.finger_device.title') }}

        </div>

        <div class="card-body">

            <div class="form-group">

                <div class="form-group">

                    <a class="btn btn-primary" href="{{ route('finger_device.index') }}">

                        {{ trans('global.back_to_list') }}

                    </a>

                </div>

                <table class="table table-bordered table-striped">

                    <tbody>

                    <tr>

                        <th>

                            {{ trans('cruds.finger_device.fields.id') }}

                        </th>

                        <td>

                            {{ $fingerDevice->id }}

                        </td>

                    </tr>

                    <tr>

                        <th>

                            {{ trans('cruds.finger_device.fields.name') }}

                        </th>

                        <td>

                            {{ $fingerDevice->name }}

                        </td>

                    </tr>

                    <tr>

                        <th>

                            {{ trans('cruds.finger_device.fields.ip') }}

                        </th>

                        <td>

                            {{ $fingerDevice->ip }}

                        </td>

                    </tr>

                    <tr>

                        <th>

                            {{ trans('cruds.finger_device.fields.serialNumber') }}

                        </th>

                        <td>

                            {{ $fingerDevice->serialNumber }}

                        </td>

                    </tr>

                    </tbody>

                </table>

                

            </div>

        </div>

    </div>

@endsection